import type { Metadata } from "next";
import { Kanit, Bungee } from "next/font/google";
import localFont from "next/font/local";
import "./styles/global.sass";
import NavBar from "./_component/NavBar";
import "animate.css";

const bungee = Bungee({
  weight: "400",
  style: "normal",
  subsets: ["latin"],
  variable: "--font-bungee",
});
const kanit = Kanit({
  weight: ["200", "600"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-kanit",
});

const chunk = localFont({
  src: "../../public/font/chunkfive.print.ttf",
  style: "normal",
  weight: "200",
  variable: "--font-chunk",
});

export const metadata: Metadata = {
  title: "Sunset Diner St. Marys",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${kanit.variable} ${bungee.variable} ${chunk.variable} font-sans`}
    >
      <body id="mainBody">
        <NavBar>{children}</NavBar>
      </body>
    </html>
  );
}
